const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const token=request=>(request.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();
async function user(env,request){const t=token(request);if(!t||!env.DB)return null;return env.DB.prepare(`SELECT id,role,name,username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?`).bind(t,new Date().toISOString()).first();}
async function ensure(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS teacher_classes (id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,name TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(owner_id,name))`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS teacher_groups (id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,name TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(owner_id,name))`).run();}
const validTeacher=u=>u&&(u.role==='admin'||u.role==='superadmin');
const ownerFor=(u,v)=>u.role==='superadmin'&&v?String(v):u.id;
async function rows(env,owner){const classes=(await env.DB.prepare(`SELECT c.id,c.name,(SELECT COUNT(*) FROM students s WHERE s.owner_id=c.owner_id AND s.grade=c.name) AS studentCount FROM teacher_classes c WHERE c.owner_id=? ORDER BY c.name`).bind(owner).all()).results||[];const groups=(await env.DB.prepare(`SELECT g.id,g.name,(SELECT COUNT(*) FROM students s WHERE s.owner_id=g.owner_id AND s.group_name=g.name) AS studentCount FROM teacher_groups g WHERE g.owner_id=? ORDER BY g.name`).bind(owner).all()).results||[];return{classes,groups}}
export async function onRequestGet({request,env}){const u=await user(env,request);if(!validTeacher(u))return json({error:'Bu bölüme erişim yetkiniz yok.'},403);try{await ensure(env);if(u.role==='superadmin'&&!new URL(request.url).searchParams.get('ownerId')){const teachers=(await env.DB.prepare(`SELECT id,name,username,status FROM users WHERE role='admin' ORDER BY name`).all()).results||[];const all=[];for(const t of teachers)all.push({...t,...await rows(env,t.id)});return json({teachers:all})}const owner=ownerFor(u,new URL(request.url).searchParams.get('ownerId'));if(u.role==='admin'&&owner!==u.id)return json({error:'Bu kayıtlar size ait değil.'},403);return json({ownerId:owner,...await rows(env,owner)})}catch(e){return json({error:e.message||'Sınıf ve grup bilgileri alınamadı.'},500)}}
export async function onRequestPost({request,env}){const u=await user(env,request);if(!validTeacher(u))return json({error:'Bu bölüme erişim yetkiniz yok.'},403);try{await ensure(env);const b=await request.json();const owner=ownerFor(u,b.ownerId);if(u.role==='admin'&&owner!==u.id)return json({error:'Bu kayıt size ait değil.'},403);const action=String(b.action||''),name=String(b.name||'').trim();if(['createClass','createGroup'].includes(action)){if(!name)return json({error:'Ad alanı gerekli.'},400);const table=action==='createClass'?'teacher_classes':'teacher_groups';await env.DB.prepare(`INSERT INTO ${table}(id,owner_id,name) VALUES(?,?,?)`).bind(crypto.randomUUID(),owner,name).run();return json({ok:true})}if(['deleteClass','deleteGroup'].includes(action)){const table=action==='deleteClass'?'teacher_classes':'teacher_groups';const ref=action==='deleteClass'?'grade':'group_name';const id=String(b.id||'');const existing=await env.DB.prepare(`SELECT id,name FROM ${table} WHERE id=? AND owner_id=?`).bind(id,owner).first();if(!existing)return json({error:'Kayıt bulunamadı.'},404);const used=await env.DB.prepare(`SELECT COUNT(*) count FROM students WHERE owner_id=? AND ${ref}=?`).bind(owner,existing.name).first();if(Number(used?.count||0)>0)return json({error:'Bu kayıt öğrenciler tarafından kullanılıyor. Önce öğrencileri başka bir sınıf veya gruba taşıyın.'},409);await env.DB.prepare(`DELETE FROM ${table} WHERE id=?`).bind(id).run();return json({ok:true})}return json({error:'Geçersiz işlem.'},400)}catch(e){if(String(e?.message||'').includes('UNIQUE constraint failed'))return json({error:'Bu ad zaten kullanılıyor.'},409);return json({error:e.message||'İşlem tamamlanamadı.'},500)}}
