(()=>{
  if(window.__mkAcademicGroups)return;
  window.__mkAcademicGroups=true;
  const token=()=>localStorage.getItem('mk_session')||'';
  const role=()=>document.querySelector('.user-chip .badge')?.textContent?.trim()||'';
  const teacher=()=>['Öğretmen','Baş Admin'].includes(role());
  const superAdmin=()=>role()==='Baş Admin';
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const api=async(path,options={})=>{const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(token()?{authorization:`Bearer ${token()}`}:{}) ,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`İşlem başarısız (${r.status})`);return d};
  const toast=(m,b=false)=>{const n=document.createElement('div');n.className=`toast ${b?'error':'ok'}`;n.textContent=m;document.body.appendChild(n);setTimeout(()=>n.remove(),3200)};
  const installStyle=()=>{if(document.getElementById('ag-style'))return;const s=document.createElement('style');s.id='ag-style';s.textContent=`.ag-modal{width:min(720px,94vw)}.ag-tabs{display:flex;gap:7px;margin-bottom:16px;padding:4px;background:#f2f5f9;border-radius:12px}.ag-tab{flex:1;border:0;background:transparent;padding:10px 12px;border-radius:9px;font-weight:800;color:#6b7a8d;cursor:pointer}.ag-tab.active{background:#fff;color:#1f3f6d;box-shadow:0 3px 10px rgba(16,34,70,.08)}.ag-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.ag-item{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px 13px;border:1px solid #e0e7ef;border-radius:12px;background:#fff}.ag-item b{font-size:13px;color:#193452}.ag-item small{display:block;margin-top:3px;color:#7b899a;font-size:10px}.ag-create{display:grid;grid-template-columns:1fr auto;gap:8px;margin-bottom:14px}.ag-create input,.ag-create select{width:100%;box-sizing:border-box;border:1px solid #d6dfeb;border-radius:10px;padding:10px 11px;font:inherit}.ag-note{padding:10px 12px;background:#f8fafc;border:1px solid #e4eaf1;border-radius:10px;color:#6e7d90;font-size:11px;margin-bottom:12px}.ag-empty{padding:18px;border:1px dashed #d8e1ec;border-radius:12px;text-align:center;color:#7d8998;font-size:12px}@media(max-width:650px){.ag-grid{grid-template-columns:1fr}.ag-create{grid-template-columns:1fr}}`;document.head.appendChild(s)};
  const ownerId=()=>document.querySelector('#student-register-modal select[name="ownerId"]')?.value||'';
  const data=async()=>api(`/api/academic-groups${superAdmin()&&ownerId()?`?ownerId=${encodeURIComponent(ownerId())}`:''}`);
  const injectSelects=async()=>{const root=document.querySelector('#student-register-modal');if(!root)return;const grade=root.querySelector('input[name="grade"]'),group=root.querySelector('input[name="groupName"]');if(!grade&&!group)return;try{const d=await data();if(grade?.parentElement){const w=grade.parentElement,v=grade.value||'';w.innerHTML=`<span>Sınıf</span><select name="grade" required><option value="">Sınıf seçin</option>${(d.classes||[]).map(x=>`<option value="${esc(x.name)}" ${x.name===v?'selected':''}>${esc(x.name)}</option>`).join('')}</select>`}const g=root.querySelector('input[name="groupName"]');if(g?.parentElement){const w=g.parentElement,v=g.value||'';w.innerHTML=`<span>Grup</span><select name="groupName"><option value="">Grup seçin</option>${(d.groups||[]).map(x=>`<option value="${esc(x.name)}" ${x.name===v?'selected':''}>${esc(x.name)}</option>`).join('')}</select>`}root.querySelector('select[name="ownerId"]')?.addEventListener('change',()=>setTimeout(injectSelects,30),{once:true})}catch{}};
  const manage=async()=>{if(!teacher())return;installStyle();const owners=superAdmin()?((await api('/api/data')).teachers||[]):[];const first=owners[0]?.id||'';let tab='classes';const m=document.createElement('div');m.className='modal-backdrop';m.innerHTML=`<div class="modal-card ag-modal"><div class="modal-head"><h2>Sınıf ve grup yönetimi</h2><button class="icon-btn" id="ag-x">×</button></div><div class="modal-body"><div class="ag-note">Burada oluşturduğun sınıf ve gruplar yalnızca kendi hesabında kullanılır. Öğrenci kaydında seçim olarak görünür.</div>${superAdmin()?`<label class="field"><span>Öğretmen</span><select id="ag-owner">${owners.map(o=>`<option value="${esc(o.id)}">${esc(o.name)}</option>`).join('')}</select></label>`:''}<div class="ag-tabs"><button class="ag-tab active" data-tab="classes">Sınıflar</button><button class="ag-tab" data-tab="groups">Gruplar</button></div><div id="ag-pane"></div></div></div>`;document.body.appendChild(m);const close=()=>m.remove();m.querySelector('#ag-x').onclick=close;m.addEventListener('click',e=>{if(e.target===m)close()});const owner=()=>m.querySelector('#ag-owner')?.value||first;const renderPane=async()=>{const d=await api(`/api/academic-groups?ownerId=${encodeURIComponent(owner())}`),list=tab==='classes'?d.classes||[]:d.groups||[];m.querySelector('#ag-pane').innerHTML=`<div class="ag-create"><input id="ag-name" maxlength="80" placeholder="Yeni ${tab==='classes'?'sınıf':'grup'} adı"><button class="btn primary" id="ag-add">Ekle</button></div><div class="ag-grid">${list.map(x=>`<div class="ag-item"><div><b>${esc(x.name)}</b><small>${x.studentCount||0} öğrenci</small></div><button class="table-btn danger" data-ag-del="${x.id}">Sil</button></div>`).join('')||'<div class="ag-empty">Henüz kayıt bulunmuyor.</div>'}</div>`;m.querySelector('#ag-add').onclick=async()=>{const name=m.querySelector('#ag-name').value.trim();if(!name)return toast('Bir ad girin.',true);try{await api('/api/academic-groups',{method:'POST',body:JSON.stringify({action:tab==='classes'?'createClass':'createGroup',name,ownerId:owner()})});toast('Kayıt eklendi.');renderPane();setTimeout(injectSelects,50)}catch(e){toast(e.message,true)}};m.querySelectorAll('[data-ag-del]').forEach(b=>b.onclick=async()=>{try{await api('/api/academic-groups',{method:'POST',body:JSON.stringify({action:tab==='classes'?'deleteClass':'deleteGroup',id:b.dataset.agDel,ownerId:owner()})});toast('Kayıt silindi.');renderPane();setTimeout(injectSelects,50)}catch(e){toast(e.message,true)}})};m.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;m.querySelectorAll('.ag-tab').forEach(x=>x.classList.toggle('active',x===b));renderPane()});m.querySelector('#ag-owner')?.addEventListener('change',renderPane);renderPane()};
  const obs=new MutationObserver(()=>{if(!teacher())return;injectSelects();const title=document.querySelector('.topbar h1')?.textContent?.trim();const head=document.querySelector('.content .panel .panel-head');if(title==='Öğrenciler'&&head&&!head.querySelector('[data-action="manage-academic"]')){const b=document.createElement('button');b.className='btn ghost';b.dataset.action='manage-academic';b.textContent='Sınıf & Grup';b.onclick=manage;head.appendChild(b)}});obs.observe(document.body,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('[data-action="new-student"]'))setTimeout(injectSelects,60)},true);
})();
