(()=>{
  if(window.__mkAcademicGroupsV2)return;window.__mkAcademicGroupsV2=true;
  const token=()=>localStorage.getItem('mk_session')||'';
  const roleText=()=>document.querySelector('.user-chip .badge')?.textContent?.trim()||'';
  const isTeacher=()=>['Öğretmen','Baş Admin'].includes(roleText());
  const isSuper=()=>roleText()==='Baş Admin';
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const api=async(path,options={})=>{const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(token()?{authorization:`Bearer ${token()}`}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`İşlem başarısız (${r.status})`);return d};
  const toast=msg=>{const n=document.createElement('div');n.className='toast error';n.textContent=msg;document.body.appendChild(n);setTimeout(()=>n.remove(),3200)};
  const style=()=>{if(document.getElementById('academic-ui-v2'))return;const s=document.createElement('style');s.id='academic-ui-v2';s.textContent=`.academic-manage-panel{margin:0 0 16px;padding:18px;border:1px solid #dfe7f1;border-radius:18px;background:linear-gradient(135deg,#fafdff,#f2f6fb);box-shadow:0 8px 24px rgba(18,42,73,.05)}.academic-manage-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.academic-manage-head h3{margin:0;font-size:17px;color:#183456}.academic-manage-head p{margin:4px 0 0;color:#718097;font-size:12px}.academic-manage-actions{display:flex;gap:8px;flex-wrap:wrap}.academic-manage-actions button{border:1px solid #d5dfeb;background:#fff;color:#29476b;padding:9px 12px;border-radius:10px;font-weight:800;cursor:pointer}.academic-manage-actions button.primary{background:#2e629f;color:#fff;border-color:#2e629f}.academic-manage-body{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.academic-pill{padding:11px 12px;border:1px solid #e1e8f1;border-radius:12px;background:#fff}.academic-pill small{display:block;color:#7b899b;margin-top:3px}.academic-modal .modal-card{width:min(700px,94vw)}.academic-modal-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.academic-modal-list{display:grid;gap:8px;margin-top:12px}.academic-modal-item{display:flex;justify-content:space-between;align-items:center;padding:11px 12px;border:1px solid #e2e8f0;border-radius:12px;background:#fafcff}.academic-modal-item small{display:block;color:#7a899c;margin-top:3px}.academic-create{display:grid;grid-template-columns:1fr auto;gap:8px;margin:10px 0}.academic-create input{border:1px solid #d6dfeb;border-radius:10px;padding:10px 12px;font:inherit}.academic-select{width:100%;border:1px solid #d6dfeb;border-radius:10px;background:#fff;padding:10px 12px;font:inherit;color:#1e395c;box-sizing:border-box}@media(max-width:700px){.academic-manage-head{flex-direction:column;align-items:stretch}.academic-body,.academic-manage-body,.academic-modal-grid{grid-template-columns:1fr}.academic-create{grid-template-columns:1fr}}`;document.head.appendChild(s)};
  const getData=async(ownerId='')=>api(`/api/academic-groups${ownerId?`?ownerId=${encodeURIComponent(ownerId)}`:''}`);
  const renderControls=async()=>{if(!isTeacher())return;const title=document.querySelector('.topbar h1')?.textContent?.trim();if(title!=='Öğrenciler')return;style();const content=document.querySelector('.content');if(!content)return;
    let anchor=content.querySelector('[data-student-academic-anchor]');if(!anchor){anchor=document.createElement('section');anchor.setAttribute('data-student-academic-anchor','');anchor.className='academic-manage-panel';const first=content.querySelector('.panel');if(first)first.before(anchor);else content.prepend(anchor)}
    const data=await getData();const classes=data.classes||[],groups=data.groups||[];anchor.innerHTML=`<div class="academic-manage-head"><div><h3>Sınıf & Grup Yönetimi</h3><p>Öğrenci kaydında kullanılacak seçimleri buradan oluşturabilirsiniz.</p></div><div class="academic-manage-actions"><button data-academic-open="class">+ Sınıf Ekle</button><button class="primary" data-academic-open="group">+ Grup Ekle</button><button data-academic-open="manage">Yönet</button></div></div><div class="academic-manage-body"><div class="academic-pill"><b>Sınıflar</b><small>${classes.length?classes.map(x=>esc(x.name)).join(' · '):'Henüz sınıf eklenmedi'}</small></div><div class="academic-pill"><b>Gruplar</b><small>${groups.length?groups.map(x=>esc(x.name)).join(' · '):'Henüz grup eklenmedi'}</small></div></div>`;
    anchor.onclick=async e=>{const b=e.target.closest('[data-academic-open]');if(!b)return;const type=b.dataset.academicOpen;if(type==='class'||type==='group'){const name=window.prompt(type==='class'?'Sınıf adı':'Grup adı');if(!name?.trim())return;try{await api('/api/academic-groups',{method:'POST',body:JSON.stringify({action:type==='class'?'createClass':'createGroup',name:name.trim()})});await renderControls();refreshStudentForm()}catch(err){toast(err.message)}}else openManager()};
    refreshStudentForm();
  };
  const refreshStudentForm=async()=>{const root=document.querySelector('#student-register-modal');if(!root||!isTeacher())return;const owner=root.querySelector('select[name="ownerId"]')?.value||'';try{const d=await getData(owner);const grade=root.querySelector('input[name="grade"],select[name="grade"]');const group=root.querySelector('input[name="groupName"],select[name="groupName"]');if(grade){const v=grade.value;const n=document.createElement('select');n.className='academic-select';n.name='grade';n.required=true;n.innerHTML=`<option value="">Sınıf seçin</option>${(d.classes||[]).map(x=>`<option value="${esc(x.name)}" ${x.name===v?'selected':''}>${esc(x.name)}</option>`).join('')}`;grade.replaceWith(n)}if(group){const v=group.value;const n=document.createElement('select');n.className='academic-select';n.name='groupName';n.innerHTML=`<option value="">Grup seçin</option>${(d.groups||[]).map(x=>`<option value="${esc(x.name)}" ${x.name===v?'selected':''}>${esc(x.name)}</option>`).join('')}`;group.replaceWith(n)}}catch(err){toast(err.message)}};
  const openManager=async()=>{if(!isTeacher())return;style();let data=await getData();const m=document.createElement('div');m.className='modal-backdrop academic-modal';m.innerHTML=`<div class="modal-card"><div class="modal-head"><h2>Sınıf ve Grup Yönetimi</h2><button class="icon-btn" data-x>×</button></div><div class="modal-body"><div class="academic-modal-grid"><div><b>Sınıflar</b><div class="academic-create"><input data-name="class" placeholder="Yeni sınıf"><button class="btn primary" data-add="class">Ekle</button></div><div class="academic-modal-list" data-list="class"></div></div><div><b>Gruplar</b><div class="academic-create"><input data-name="group" placeholder="Yeni grup"><button class="btn primary" data-add="group">Ekle</button></div><div class="academic-modal-list" data-list="group"></div></div></div></div></div>`;document.body.appendChild(m);const close=()=>m.remove();m.querySelector('[data-x]').onclick=close;const render=async()=>{data=await getData();for(const type of ['class','group']){const arr=type==='class'?data.classes||[]:data.groups||[];m.querySelector(`[data-list="${type}"]`).innerHTML=arr.map(x=>`<div class="academic-modal-item"><div><b>${esc(x.name)}</b><small>${Number(x.studentCount||0)} öğrenci</small></div><button class="table-btn danger" data-del="${type}" data-id="${esc(x.id)}" ${Number(x.studentCount||0)?'disabled':''}>Sil</button></div>`).join('')||'<div class="academic-modal-item">Henüz kayıt yok.</div>'}};m.onclick=async e=>{const a=e.target.closest('[data-add]');if(a){const type=a.dataset.add,name=m.querySelector(`[data-name="${type}"]`).value.trim();if(!name)return;try{await api('/api/academic-groups',{method:'POST',body:JSON.stringify({action:type==='class'?'createClass':'createGroup',name})});m.querySelector(`[data-name="${type}"]`).value='';await render();await renderControls();refreshStudentForm()}catch(err){toast(err.message)}}const d=e.target.closest('[data-del]');if(d&&!d.disabled){try{await api('/api/academic-groups',{method:'POST',body:JSON.stringify({action:d.dataset.del==='class'?'deleteClass':'deleteGroup',id:d.dataset.id})});await render();await renderControls();refreshStudentForm()}catch(err){toast(err.message)}}};render()};
  new MutationObserver(()=>setTimeout(()=>renderControls().catch(()=>{}),30)).observe(document.body,{childList:true,subtree:true});setInterval(()=>renderControls().catch(()=>{}),500);setTimeout(()=>renderControls().catch(()=>{}),120);
  document.addEventListener('click',e=>{if(e.target.closest('[data-action="new-student"]'))setTimeout(()=>refreshStudentForm(),120)},true);
})();