const patchState={data:null};
const today=()=>new Date().toISOString().slice(0,10);
const token=()=>localStorage.getItem('mk_session')||'';
async function api(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};if(token())headers.authorization=`Bearer ${token()}`;const r=await fetch(`/api${path}`,{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`İşlem başarısız (${r.status})`);return d;}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function showModal(title,html,onSubmit){document.querySelector('#patch-modal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div id="patch-modal" class="modal-backdrop"><div class="modal-card"><div class="modal-head"><h2>${esc(title)}</h2><button type="button" class="icon-btn" id="patch-close">×</button></div><form id="patch-form" class="modal-body form-grid">${html}<div class="form-actions"><button class="btn primary">Kaydet</button></div></form></div></div>`);document.querySelector('#patch-close').onclick=()=>document.querySelector('#patch-modal')?.remove();document.querySelector('#patch-form').onsubmit=async e=>{e.preventDefault();try{await onSubmit(new FormData(e.currentTarget));document.querySelector('#patch-modal')?.remove();location.reload()}catch(err){alert(err.message)}};}
function field(label,name,value='',type='text',extra=''){return `<label class="field"><span>${esc(label)}</span><input name="${esc(name)}" value="${esc(value)}" type="${type}" ${extra}></label>`;}
function selectField(label,name,opts,value='',extra=''){return `<label class="field"><span>${esc(label)}</span><select name="${esc(name)}" ${extra}>${opts.map(o=>`<option value="${esc(o.value)}" ${String(o.value)===String(value)?'selected':''}>${esc(o.label)}</option>`).join('')}</select></label>`;}
function dayHours(){return Array.from({length:16},(_,i)=>i+8).map(h=>({value:`${String(h).padStart(2,'0')}:00`,label:`${String(h).padStart(2,'0')}:00`}));}
function addLessonButton(){const head=document.querySelector('.calendar-layout .panel:first-child .panel-head');if(!head||document.querySelector('#patch-new-lesson'))return;const wrap=document.createElement('div');wrap.className='actions';wrap.innerHTML='<button class="btn primary" id="patch-new-lesson">+ Ders Planla</button>';head.appendChild(wrap);document.querySelector('#patch-new-lesson').onclick=()=>lessonModal();}
function lessonModal(){const d=patchState.data||{};const students=d.students||[];const teachers=d.teachers||[];showModal('Ders planla',`${selectField('Öğrenci','studentId',students.map(s=>({value:s.id,label:s.name})),students[0]?.id||'')}${d.user?.role==='superadmin'?selectField('Öğretmen','ownerId',teachers.map(t=>({value:t.id,label:t.name})),teachers[0]?.id||''):''}${field('Ders adı','title','Matematik Dersi')}${field('Tarih','date','', 'date',`min="${today()}"`)}${selectField('Saat','start',dayHours(),'08:00')}<p class="form-note">Kapalı, dolu veya çakışan saatler sunucu tarafında engellenir.</p>`,async fd=>{await api('/data',{method:'POST',body:JSON.stringify({type:'lesson',studentId:fd.get('studentId'),ownerId:fd.get('ownerId'),title:fd.get('title'),date:fd.get('date'),start:fd.get('start')})})});}
function addStudentRequestButtons(){if(!patchState.data)return;const role=patchState.data.user?.role;if(role!=='student'&&role!=='parent')return;const cards=[...document.querySelectorAll('.lesson-card')];const lessons=patchState.data.lessons||[];cards.forEach((card,i)=>{if(card.querySelector('.patch-request'))return;const lesson=lessons.filter(l=>l.date>=today())[i];if(!lesson)return;const actions=card.querySelector('.row-actions')||card.appendChild(Object.assign(document.createElement('div'),{className:'row-actions'}));const b=document.createElement('button');b.className='btn tiny patch-request';b.textContent='Saat Değiştir';b.onclick=()=>requestModal(lesson);actions.appendChild(b);});}
function requestModal(l){const own=patchState.data.students||[];const student=own.find(s=>s.id===l.studentId)||own[0];if(!student)return;showModal('Saat değişikliği talebi',`${field('Mevcut ders','current',`${l.date} ${l.start}–${l.end}`,'text','disabled')}${field('Yeni tarih','requestedDate','', 'date',`min="${today()}"`)}${selectField('Yeni saat','requestedStart',dayHours(),'08:00')}${field('Açıklama','reason')}`,async fd=>{await api('/data',{method:'POST',body:JSON.stringify({type:'changeRequest',studentId:student.id,lessonId:l.id,requestedDate:fd.get('requestedDate'),requestedStart:fd.get('requestedStart'),reason:fd.get('reason')})})});}
function apply(){const title=document.querySelector('.topbar h1')?.textContent.trim();if(title==='Takvim')addLessonButton();if(title==='Dersler')addStudentRequestButtons();}
async function boot(){try{patchState.data=await api('/data');apply();new MutationObserver(()=>apply()).observe(document.body,{childList:true,subtree:true});}catch{}}
boot();
