import './styles.css';

const app = document.querySelector('#app');
const BRAND = 'Matematik Koçum';
const TODAY = () => new Date().toISOString().slice(0,10);
const HOURS = Array.from({length:16},(_,i)=>i+8);
let state={user:null,students:[],lessons:[],requests:[],exams:[],evaluations:[],coaching:[]};
let page='dashboard';
let month=new Date(new Date().getFullYear(),new Date().getMonth(),1);

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const token=()=>localStorage.getItem('mk_session')||'';
const setToken=t=>t?localStorage.setItem('mk_session',t):localStorage.removeItem('mk_session');
const roleName=r=>({superadmin:'Baş Admin',admin:'Öğretmen',student:'Öğrenci',parent:'Veli'}[r]||r);
const serviceHas=(s,type)=>{const v=s?.serviceType||'ozel_ders';return type==='coaching'?['kocluk','both','ikisi'].includes(v):['ozel_ders','both','ikisi'].includes(v)};
const tone=n=>Number(n)<40?'red':Number(n)<70?'orange':'green';
const badge=(t,c='soft')=>`<span class="badge ${c}">${esc(t)}</span>`;

async function api(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};if(token())headers.authorization=`Bearer ${token()}`;const res=await fetch(`/api${path}`,{...options,headers});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`İstek başarısız (${res.status})`);return data;}
async function load(){if(!token()){state={user:null,students:[],lessons:[],requests:[],exams:[],evaluations:[],coaching:[]};return;}const data=await api('/data');state={...state,...data,user:data.user};}
function loginView(){return `<div class="login-page"><div class="login-card"><div class="brand centered"><span class="brand-mark">√</span><span>${BRAND}</span></div><span class="eyebrow">MATEMATİK KOÇUM</span><h1>Matematiği ezberleme, mantığını keşfet.</h1><p>Öğrenci, veli ve öğretmen süreçlerini tek merkezden yöneten çalışma alanı.</p><form id="login-form"><label>Kullanıcı adı<input name="username" autocomplete="username" required></label><label>Şifre<input name="password" type="password" autocomplete="current-password" required></label><button class="btn primary">Giriş Yap</button><div id="login-error" class="error"></div></form></div></div>`}
function nav(id,label,icon){return `<button class="nav-item ${page===id?'active':''}" data-page="${id}">${icon}<span>${label}</span></button>`}
function layout(content){const r=state.user.role,teacher=r==='admin'||r==='superadmin';return `<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">√</span><span>${BRAND}</span></div><div class="sidebar-label">${teacher?'YÖNETİM':'PANEL'}</div>${nav('dashboard','Genel Bakış','▦')}${teacher?nav('students','Öğrenciler','◉'):''}${teacher?nav('calendar','Takvim','◫'):nav('schedule','Ders Programı','◷')}${teacher?nav('requests','Saat Talepleri','↔'):''}${nav('exams','Denemeler & Kazanımlar','▤')}${r==='parent'?nav('evaluation','Öğretmen Değerlendirmesi','◈'):''}${(r==='student'||r==='parent')&&serviceHas(state.user.student,'coaching')?nav('coaching','Koçluk','◎'):''}<div class="sidebar-spacer"></div><button class="nav-item" id="logout">↩ <span>Çıkış Yap</span></button></aside><main class="main"><header class="topbar"><div><div class="eyebrow">${BRAND.toUpperCase()}</div><h1>${title()}</h1></div><div class="user-chip"><span>${esc(state.user.name)}</span>${badge(roleName(r))}</div></header><section class="content">${content}</section></main></div>`}
function title(){return({dashboard:'Genel Bakış',students:'Öğrenciler',calendar:'Takvim',schedule:'Ders Programı',requests:'Saat Talepleri',exams:'Denemeler & Kazanımlar',evaluation:'Öğretmen Değerlendirmesi',coaching:'Koçluk'})[page]||'Genel Bakış'}
function dashboard(){const pending=state.requests.filter(x=>x.status==='pending').length;return `<div class="hero-strip"><div><span class="eyebrow">KONTROL MERKEZİ</span><h2>Her şey tek yerde.</h2><p>Merkezi veri, rol bazlı erişim ve çakışma kontrollü çalışma alanı.</p></div></div><div class="stat-grid"><article class="stat-card"><span>Öğrenciler</span><strong>${state.students.length}</strong><small>Yetkin dahilindeki hesaplar</small></article><article class="stat-card"><span>Planlı Ders</span><strong>${state.lessons.length}</strong><small>Takvim kayıtları</small></article><article class="stat-card"><span>Bekleyen Talep</span><strong>${pending}</strong><small>Saat değişikliği</small></article><article class="stat-card"><span>Sınav</span><strong>${state.exams.length}</strong><small>Deneme ve kazanım</small></article></div><div class="card-grid two"><section class="panel"><div class="panel-head"><div><h2>Hızlı işlemler</h2><p>Sık kullanılan alanlara geç.</p></div></div><div class="quick-grid">${state.user.role!=='student'&&state.user.role!=='parent'?'<button class="quick" data-page="students">👤<b>Öğrenciler</b><small>Hesap ve hizmet tipi</small></button>':''}<button class="quick" data-page="${state.user.role==='student'||state.user.role==='parent'?'schedule':'calendar'}">◫<b>Takvim</b><small>Ders ve uygunluk</small></button><button class="quick" data-page="exams">▤<b>Sınavlar</b><small>Sonuç ve kazanım</small></button>${state.user.role==='parent'?'<button class="quick" data-page="evaluation">◈<b>Değerlendirme</b><small>Öğretmen görüşü</small></button>':''}</div></section><section class="panel"><div class="panel-head"><div><h2>Sistem durumu</h2><p>Bu yapı merkezi veriye göre çalışır.</p></div></div><div class="principles"><div>☁️ Merkezi veri</div><div>🔒 Rol bazlı erişim</div><div>📅 Geçmiş kilitli</div><div>🟢 Yeşil saatler seçilebilir</div></div></section></div>`}
function students(){return `<section class="panel"><div class="panel-head"><div><h2>Öğrenciler</h2><p>Öğrenci hizmet tipleri ve öğretmen ilişkileri.</p></div><button class="btn primary" id="new-student">+ Öğrenci Ekle</button></div><div class="table-wrap"><table><thead><tr><th>Öğrenci</th><th>Sınıf</th><th>Hizmet</th><th>Grup</th><th></th></tr></thead><tbody>${state.students.map(s=>`<tr><td><b>${esc(s.name)}</b></td><td>${esc(s.grade||'')}</td><td>${serviceHas(s,'lesson')&&serviceHas(s,'coaching')?badge('Özel Ders + Koçluk','green'):serviceHas(s,'lesson')?badge('Özel Ders','blue'):badge('Koçluk','orange')}</td><td>${esc(s.groupName||s.group||'')}</td><td><button class="table-btn" data-student-id="${s.id}">Detay</button></td></tr>`).join('')}</tbody></table></div></section>`}
function calendar(){const y=month.getFullYear(),m=month.getMonth(),days=new Date(y,m+1,0).getDate(),first=(new Date(y,m,1).getDay()+6)%7,label=month.toLocaleDateString('tr-TR',{month:'long',year:'numeric'});let html=Array.from({length:first},()=>'<div class="calendar-cell muted-cell"></div>').join('');for(let d=1;d<=days;d++){const date=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,past=date<TODAY(),lessons=state.lessons.filter(x=>x.date===date);html+=`<button class="calendar-cell ${date===TODAY()?'today':''} ${past?'past':''}" data-date="${date}" ${past?'disabled':''}><b>${d}</b><div class="cell-bars">${lessons.slice(0,3).map(l=>`<span class="bar orange">${esc(l.start)} ${esc(l.title||'Ders')}</span>`).join('')}<span class="bar green">${Math.max(0,HOURS.length-lessons.length)} açık</span></div></button>`}return `<section class="panel"><div class="panel-head"><div><span class="eyebrow">AYLIK TAKVİM</span><h2>${label}</h2><p>🟢 Açık · 🟠 Dolu · 🔴 Kapalı · Geçmiş günler düzenlenemez.</p></div><div class="toolbar"><button class="btn ghost" id="prev-month">‹</button><button class="btn ghost" id="today-month">Bugün</button><button class="btn ghost" id="next-month">›</button></div></div><div class="weekdays">${['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar-grid">${html}</div></section>`}
function schedule(){return `<section class="panel"><div class="panel-head"><div><span class="eyebrow">DERS PROGRAMI</span><h2>Yaklaşan dersler</h2><p>Geçmiş dersler üzerinde değişiklik yapılamaz.</p></div></div>${state.lessons.filter(x=>x.date>=TODAY()).length?state.lessons.filter(x=>x.date>=TODAY()).map(l=>`<div class="lesson-row"><div><b>${esc(l.title||'Matematik Dersi')}</b><small>${esc(l.date)} · ${esc(l.start)}–${esc(l.end)}</small></div>${badge('Planlandı','green')}</div>`).join(''):'<div class="empty">Yaklaşan ders bulunmuyor.</div>'}</section>`}
function requests(){const pending=state.requests.filter(x=>x.status==='pending');return `<section class="panel"><div class="panel-head"><div><span class="eyebrow">TALEPLER</span><h2>Bekleyen saat değişiklikleri</h2><p>Onay verilmeden mevcut ders taşınmaz.</p></div></div>${pending.length?pending.map(r=>`<article class="request-card"><div><b>${esc(r.studentName||'Öğrenci')}</b><small>${esc(r.currentDate)} ${esc(r.currentStart)} → ${esc(r.requestedDate)} ${esc(r.requestedStart)}</small><p>${esc(r.reason||'Açıklama yok.')}</p></div><div class="actions"><button class="btn primary" data-request="approve" data-id="${r.id}">Onayla</button><button class="btn ghost" data-request="reject" data-id="${r.id}">Reddet</button></div></article>`).join(''):'<div class="empty">Bekleyen talep yok.</div>'}</section>`}
function exams(){return `<section class="panel"><div class="panel-head"><div><span class="eyebrow">ANALİZ</span><h2>Denemeler & Kazanımlar</h2><p>Sınavlar, sorular ve kazanım analizi.</p></div>${['admin','superadmin'].includes(state.user.role)?'<button class="btn primary" id="new-exam">+ Yeni Sınav</button>':''}</div><div class="exam-grid">${state.exams.length?state.exams.map(e=>`<article class="exam-card"><div class="exam-card-top">${badge(e.type||'Deneme','soft')}<small>${esc(e.date||'')}</small></div><h3>${esc(e.title)}</h3><p>${esc(e.evaluation||'Sınav sonucu ve soru analizi burada görünecek.')}</p>${e.score!=null?`<strong>${esc(e.score)} puan</strong>`:''}</article>`).join(''):'<div class="empty">Henüz sınav bulunmuyor. Öğretmen sınav oluşturduğunda burada görünecek.</div>'}</div></section>`}
function coaching(){const p=state.coaching?.[0]||{};return `<section class="panel"><div class="panel-head"><div><span class="eyebrow">KOÇLUK</span><h2>Koçluk paneli</h2><p>Yalnızca koçluk hizmeti olan öğrenciler görür.</p></div></div><div class="coach-grid"><article><span>Haftalık hedef</span><strong>${esc(p.weeklyGoal||'Henüz belirlenmedi')}</strong></article><article><span>Odak</span><strong>${esc(p.focus||'Henüz belirlenmedi')}</strong></article><article><span>Alışkanlık</span><strong>${esc(p.habits||'Henüz belirlenmedi')}</strong></article><article><span>Sonraki görüşme</span><strong>${esc(p.nextMeeting||'Planlanmadı')}</strong></article></div></section>`}
function evaluation(){const e=state.evaluations?.[0]||{},scores=[['Konu anlama',e.understanding],['Ödev düzeni',e.homeworkRate],['Ders katılımı',e.attendance],['Soru çözme',e.problemSolving],['Dikkat & odak',e.focus],['Süreklilik',e.consistency]];return `<section class="panel"><div class="panel-head"><div><span class="eyebrow">DEĞERLENDİRME</span><h2>Öğretmen değerlendirmesi</h2><p>Veli için ayrıntılı, görsel performans özeti.</p></div></div><div class="score-grid">${scores.map(([l,v])=>`<article class="score-card ${tone(v)}"><strong>${Number(v)||0}</strong><span>${l}</span></article>`).join('')}</div><div class="note-grid"><article><b>Güçlü yönler</b><p>${esc(e.strengths||'Henüz eklenmedi.')}</p></article><article><b>Gelişim alanı</b><p>${esc(e.focusArea||'Henüz eklenmedi.')}</p></article><article><b>Sonraki hedef</b><p>${esc(e.nextGoal||'Henüz eklenmedi.')}</p></article></div></section>`}
function render(){if(!state.user){app.innerHTML=loginView();bind();return}let body=dashboard();if(page==='students')body=students();else if(page==='calendar')body=calendar();else if(page==='schedule')body=schedule();else if(page==='requests')body=requests();else if(page==='exams')body=exams();else if(page==='coaching')body=coaching();else if(page==='evaluation')body=evaluation();app.innerHTML=layout(body);bind()}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{page=b.dataset.page;render()}));document.querySelector('#logout')?.addEventListener('click',async()=>{try{await api('/auth',{method:'DELETE'})}catch{}setToken('');state.user=null;render()});document.querySelector('#login-form')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),error=document.querySelector('#login-error');error.textContent='';try{const r=await api('/auth',{method:'POST',body:JSON.stringify({username:fd.get('username'),password:fd.get('password')})});setToken(r.user.token);await load();page='dashboard';render()}catch(err){error.textContent=err.message}});document.querySelector('#prev-month')?.addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);render()});document.querySelector('#next-month')?.addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);render()});document.querySelector('#today-month')?.addEventListener('click',()=>{month=new Date(new Date().getFullYear(),new Date().getMonth(),1);render()});document.querySelectorAll('[data-request]').forEach(b=>b.addEventListener('click',async()=>{try{await api('/data',{method:'POST',body:JSON.stringify({type:'requestDecision',id:b.dataset.id,action:b.dataset.request})});await load();render()}catch(e){alert(e.message)}}))}
(async()=>{try{await load()}catch{setToken('');state.user=null}render()})();
