(()=>{
  if(window.__mkPremiumUi)return; window.__mkPremiumUi=true;
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const roleLabel=()=>document.querySelector('.user-chip .badge')?.textContent?.trim()||'';
  const teacher=()=>['Öğretmen','Baş Admin'].includes(roleLabel());
  const page=()=>document.querySelector('.topbar h1')?.textContent?.trim()||'';
  function styles(){if(document.getElementById('premium-ui-styles'))return;const s=document.createElement('style');s.id='premium-ui-styles';s.textContent=`
    :root{--mk-ink:#13233d;--mk-muted:#718097;--mk-border:#e4eaf2;--mk-soft:#f7f9fc;--mk-primary:#183b72;--mk-primary-2:#2a5aa0;--mk-shadow:0 14px 42px rgba(17,38,68,.07)}
    body{letter-spacing:-.01em}.content{padding-top:30px}.panel,.stat,.exam-card,.lesson-card,.request-card,.score-card,.metric{transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}.panel:hover,.stat:hover,.exam-card:hover,.lesson-card:hover,.request-card:hover,.metric:hover{box-shadow:var(--mk-shadow)}
    .panel{box-shadow:0 6px 24px rgba(16,34,70,.035)}.panel-head h2{letter-spacing:-.02em}.btn{transition:transform .15s ease,box-shadow .15s ease,background .15s ease}.btn:hover{box-shadow:0 7px 16px rgba(24,59,114,.10)}
    .mk-hero{position:relative;overflow:hidden;background:linear-gradient(135deg,#122b52 0%,#1d4c8d 100%);color:#fff;border-radius:22px;padding:26px 28px;margin:0 0 18px;box-shadow:0 18px 42px rgba(18,55,105,.18)}
    .mk-hero:after{content:"";position:absolute;width:220px;height:220px;border-radius:50%;right:-60px;top:-100px;background:rgba(255,255,255,.08);box-shadow:-55px 125px 0 20px rgba(255,255,255,.035)}
    .mk-hero-inner{position:relative;z-index:1;display:flex;justify-content:space-between;gap:20px;align-items:center}.mk-hero h2{margin:0;font-size:27px;letter-spacing:-.03em}.mk-hero p{margin:7px 0 0;color:rgba(255,255,255,.78);font-size:13px}.mk-hero-meta{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.mk-hero .mk-chip{padding:8px 11px;border-radius:999px;background:rgba(255,255,255,.12);font-size:11px;font-weight:800}
    .mk-quick{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:0 0 18px}.mk-quick button{border:1px solid var(--mk-border);background:#fff;border-radius:16px;padding:15px;text-align:left;display:grid;gap:6px;cursor:pointer;transition:all .18s ease;box-shadow:0 6px 18px rgba(16,34,70,.035)}.mk-quick button:hover{transform:translateY(-2px);border-color:#c6d4e7;box-shadow:0 12px 28px rgba(16,34,70,.08)}.mk-quick .mk-icon{width:34px;height:34px;border-radius:10px;background:#edf3ff;color:#2b5b9d;display:grid;place-items:center;font-weight:900}.mk-quick b{font-size:13px;color:var(--mk-ink)}.mk-quick span:last-child{font-size:11px;color:var(--mk-muted)}
    .mk-section-label{display:flex;align-items:center;gap:8px;margin:10px 2px 10px;color:#6f7e94;font-size:11px;font-weight:900;letter-spacing:.09em;text-transform:uppercase}.mk-section-label:after{content:"";height:1px;background:var(--mk-border);flex:1}
    .mk-search{display:flex;align-items:center;gap:8px;background:#fff;border:1px solid var(--mk-border);border-radius:12px;padding:8px 11px;min-width:220px;box-shadow:0 4px 14px rgba(16,34,70,.03)}.mk-search input{border:0;outline:none;width:100%;font-size:13px;color:var(--mk-ink);background:transparent}.mk-search span{color:#93a0b1;font-size:15px}
    .mk-fade{animation:mkFade .28s ease both}@keyframes mkFade{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:none}}
    .mk-empty{padding:24px;border:1px dashed #ccd7e5;background:#fbfcfe;border-radius:14px;text-align:center;color:#7a8799}.mk-empty b{display:block;color:#4f6078;margin-bottom:5px}
    .user-chip{background:#fff;border:1px solid var(--mk-border);padding:7px 10px;border-radius:999px;box-shadow:0 5px 16px rgba(16,34,70,.035)}
    table tbody tr{transition:background .15s ease}table tbody tr:hover{background:#fbfcfe}th{position:sticky;top:0;background:#fff;z-index:1}
    @media(max-width:900px){.mk-quick{grid-template-columns:1fr 1fr}.mk-hero-inner{align-items:flex-start;flex-direction:column}.mk-hero h2{font-size:23px}.mk-search{width:100%}}
    @media(max-width:560px){.mk-quick{grid-template-columns:1fr}.mk-hero{padding:22px}.mk-hero h2{font-size:21px}}
  `;document.head.appendChild(s)}
  function addHero(){if(page()!=='Genel Bakış'||document.querySelector('.mk-hero'))return;const content=document.querySelector('.content');const stats=content?.querySelector('.stats');if(!stats)return;const name=document.querySelector('.user-chip b')?.textContent?.trim()||'Kullanıcı';const hero=document.createElement('section');hero.className='mk-hero mk-fade';hero.innerHTML=`<div class="mk-hero-inner"><div><h2>Hoş geldin, ${esc(name)}.</h2><p>Bugünkü derslerini, öğrencilerini ve sınavlarını tek ekrandan takip et.</p></div><div class="mk-hero-meta"><span class="mk-chip">${new Date().toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long'})}</span><span class="mk-chip">${esc(roleLabel())}</span></div></div>`;stats.before(hero)}
  function addQuick(){if(page()!=='Genel Bakış'||document.querySelector('.mk-quick'))return;const content=document.querySelector('.content');if(!content)return;const grid=document.createElement('div');grid.className='mk-quick mk-fade';const items=[];if(teacher())items.push(['Öğrenci ekle','Yeni öğrenci kaydı oluştur','+','new-student']);if(teacher())items.push(['Takvim','Dersleri ve saatleri yönet','▦','calendar']);items.push(['Denemeler','Sınav ve sonuçlara geç','▤','exams']);if(teacher())items.push(['Değerlendirme','Öğrenci gelişimini güncelle','◈','evaluation']);grid.innerHTML=items.map(x=>`<button data-mk-quick="${esc(x[3])}"><span class="mk-icon">${x[2]}</span><b>${esc(x[0])}</b><span>${esc(x[1])}</span></button>`).join('');const hero=document.querySelector('.mk-hero');(hero||content.firstElementChild)?.after(grid);grid.querySelectorAll('[data-mk-quick]').forEach(b=>b.onclick=()=>{const a=b.dataset.mkQuick;if(a==='new-student')document.querySelector('[data-action="new-student"]')?.click();else document.querySelector(`[data-page="${a}"]`)?.click()});}
  function addSearch(){const p=page();if(!['Öğrenciler','Denemeler'].includes(p))return;if(document.querySelector('.mk-search'))return;const head=document.querySelector('.content .panel .panel-head');if(!head)return;const box=document.createElement('label');box.className='mk-search';box.innerHTML='<span>⌕</span><input autocomplete="off" placeholder="Ara...">';head.appendChild(box);const input=box.querySelector('input');input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();if(p==='Öğrenciler'){document.querySelectorAll('tbody tr').forEach(tr=>{tr.style.display=!q||tr.textContent.toLowerCase().includes(q)?'':'none'})}else{document.querySelectorAll('.exam-card').forEach(card=>{card.style.display=!q||card.textContent.toLowerCase().includes(q)?'':'none'})}})}
  function decorate(){styles();document.querySelectorAll('.panel,.stat,.exam-card,.lesson-card,.request-card').forEach((el,i)=>{if(!el.dataset.mkAnimated){el.dataset.mkAnimated='1';el.style.animationDelay=Math.min(i*18,120)+'ms';el.classList.add('mk-fade')}});addHero();addQuick();addSearch();}
  const observer=new MutationObserver(()=>{if(window.__mkPremiumRendering)return;window.__mkPremiumRendering=true;queueMicrotask(()=>{try{decorate()}finally{window.__mkPremiumRendering=false}})});observer.observe(document.body,{childList:true,subtree:true});
  document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){const s=document.querySelector('.mk-search input');if(s){e.preventDefault();s.focus()}}if(e.key==='Escape'){document.querySelector('.modal-backdrop')?.remove();document.querySelector('.sidebar.open')?.classList.remove('open')}});
  decorate();
})();
